<?xml version="1.0" encoding="utf-8"?><Database Name="TeamManager" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Team_home_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Team_away_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Match_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Score_home" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score_away" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Match_Statistic" Member="Statistics" ThisKey="ID" OtherKey="Match_id" Type="Statistic" />
      <Association Name="Team_Match" Member="Team" ThisKey="Team_home_id" OtherKey="ID" Type="Team" IsForeignKey="true" />
      <Association Name="Team_Match1" Member="Team1" ThisKey="Team_away_id" OtherKey="ID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Team_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date_of_birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Contract_start_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Contract_end_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Player_Statistic" Member="Statistics" ThisKey="ID" OtherKey="Player_id" Type="Statistic" />
      <Association Name="Team_Player" Member="Team" ThisKey="Team_id" OtherKey="ID" Type="Team" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Statistics]" Member="Statistics">
    <Type Name="Statistic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Match_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Goals" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Assists" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Yellow_cards" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Red_cards" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Minutes_played" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Association Name="Match_Statistic" Member="Match" ThisKey="Match_id" OtherKey="ID" Type="Match" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Player_Statistic" Member="Player" ThisKey="Player_id" OtherKey="ID" Type="Player" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Coach" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Founded_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="League" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Home_town" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Team_Match" Member="Matches" ThisKey="ID" OtherKey="Team_home_id" Type="Match" />
      <Association Name="Team_Match1" Member="Matches1" ThisKey="ID" OtherKey="Team_away_id" Type="Match" />
      <Association Name="Team_Player" Member="Players" ThisKey="ID" OtherKey="Team_id" Type="Player" />
    </Type>
  </Table>
</Database>